name: deploy
on:
  push: { tags: ['deploy-*'] }
  workflow_dispatch: {}
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    uses: mosni/infrastructure/.github/workflows/deploy.yml@main
